// ============================================================
// GrantAI — Centralized Service Mock Data
// Structured to mirror expected backend API responses.
// Every value is researcher-profile-derived after AI analysis.
// ============================================================

// ---------- Researcher Profile (uploaded & AI-analyzed) ----------
export const researcherProfile = {
  id: 'usr_001',
  name: 'Dr. Sarah Chen',
  email: 'sarah.chen@stanford.edu',
  institution: 'Stanford University',
  department: 'Computer Science',
  country: 'USA',
  position: 'Associate Professor',
  yearsOfExperience: 12,
  avatar: null,
  role: 'Principal Investigator',
  joinedDate: '2025-09-15',
  researchInterests: ['Artificial Intelligence', 'Medical Imaging', 'Natural Language Processing', 'Healthcare Informatics'],
  keywords: ['Deep Learning', 'CNN', 'Transformer Models', 'Clinical NLP', 'Radiology AI', 'Multi-modal Learning', 'Federated Learning'],
  preferredFundingType: 'Research Grant',
  publications: 47,
  hIndex: 22,
  profileAnalyzedAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
};

// Alias for backward compat
export const currentUser = researcherProfile;

export const sidebarLinks = [
  { name: 'Dashboard', path: '/dashboard', icon: 'LayoutDashboard' },
  { name: 'Discover Grants', path: '/discover', icon: 'Search' },
  { name: 'Planner', path: '/planner', icon: 'CalendarCheck' },
  { name: 'Notifications', path: '/notifications', icon: 'Bell' },
  { name: 'Settings', path: '/settings', icon: 'Settings' },
];

// ---------- AI-Generated Insight Summary ----------
export const aiInsightSummary = {
  text: 'Your uploaded research profile has been analyzed. We found 18 highly relevant grant opportunities matching your expertise in Artificial Intelligence and Medical Imaging across 6 funding agencies.',
  matchingGrantsCount: 18,
  highPriorityCount: 7,
  newSinceLastVisit: 3,
  analyzedKeywords: ['Artificial Intelligence', 'Medical Imaging', 'Clinical NLP', 'Deep Learning'],
};

// ---------- Recommended Adjacent Research Areas ----------
export const recommendedAreas = [
  { id: 'ra_01', name: 'Computer Vision', relevance: 94 },
  { id: 'ra_02', name: 'Digital Health', relevance: 91 },
  { id: 'ra_03', name: 'Explainable AI', relevance: 89 },
  { id: 'ra_04', name: 'Federated Learning', relevance: 87 },
  { id: 'ra_05', name: 'Edge AI', relevance: 84 },
  { id: 'ra_06', name: 'Precision Medicine', relevance: 82 },
  { id: 'ra_07', name: 'Biomedical NLP', relevance: 80 },
  { id: 'ra_08', name: 'Responsible AI', relevance: 78 },
];

// ---------- Dashboard Analytics (researcher-derived) ----------
export const dashboardData = {
  stats: [
    {
      id: 'stat_01',
      title: 'Matching Grants',
      value: 18,
      trend: { value: 12.5, direction: 'up' },
      icon: 'Search',
      color: 'blue',
      description: 'Grants matching your AI & Medical Imaging profile',
    },
    {
      id: 'stat_02',
      title: 'High Priority',
      value: 7,
      trend: { value: 3, direction: 'up' },
      icon: 'Zap',
      color: 'violet',
      description: 'Opportunities with >90% match score',
    },
    {
      id: 'stat_03',
      title: 'Avg Match Score',
      value: 87,
      suffix: '%',
      trend: { value: 4.2, direction: 'up' },
      icon: 'Target',
      color: 'emerald',
      description: 'Based on your research keywords & publications',
    },
    {
      id: 'stat_04',
      title: 'Funding Potential',
      value: 5850000,
      prefix: '$',
      format: 'currency',
      trend: { value: 8.3, direction: 'up' },
      icon: 'DollarSign',
      color: 'amber',
      description: 'Total available across matching grants',
    },
    {
      id: 'stat_05',
      title: 'Upcoming Deadlines',
      value: 5,
      trend: { value: 1, direction: 'down' },
      icon: 'Clock',
      color: 'rose',
      description: 'Grants closing within 60 days',
    },
    {
      id: 'stat_06',
      title: 'Matching Agencies',
      value: 6,
      trend: { value: 2, direction: 'up' },
      icon: 'Building2',
      color: 'cyan',
      description: 'NSF, NIH, ANRF, UKRI, Horizon Europe, DARPA',
    },
  ],

  activities: [
    {
      id: 'act_01',
      type: 'profile',
      title: 'Research Profile Analyzed',
      description: 'AI analyzed 47 publications and 7 research keywords from your uploaded CV.',
      timestamp: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
      icon: 'Sparkles',
    },
    {
      id: 'act_02',
      type: 'match',
      title: '18 New Matches Discovered',
      description: 'Profile analysis identified 18 grant opportunities across AI, Medical Imaging, and NLP.',
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 1).toISOString(),
      icon: 'Target',
    },
    {
      id: 'act_03',
      type: 'grant_saved',
      title: 'Grant Bookmarked',
      description: 'Saved "AI-Driven Healthcare Diagnostics" (NIH) — 96% match score.',
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
      icon: 'Bookmark',
    },
    {
      id: 'act_04',
      type: 'planner',
      title: 'Planner Auto-Generated',
      description: 'AI created a 4-week application plan for NIH AI Healthcare grant.',
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
      icon: 'CheckCircle',
    },
    {
      id: 'act_05',
      type: 'reminder',
      title: 'Deadline Alert Set',
      description: 'Automatic reminder configured for DOE Climate Prediction deadline (Aug 30).',
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
      icon: 'Bell',
    },
    {
      id: 'act_06',
      type: 'application',
      title: 'Application Draft Started',
      description: 'Began DARPA Ethical AI Frameworks proposal using your research profile data.',
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
      icon: 'Send',
    },
  ],

  charts: {
    funding: [
      { name: 'NSF', value: 1445000, fill: '#3b82f6' },
      { name: 'NIH', value: 1400000, fill: '#8b5cf6' },
      { name: 'ANRF', value: 620000, fill: '#06b6d4' },
      { name: 'UKRI', value: 540000, fill: '#f59e0b' },
      { name: 'Horizon EU', value: 950000, fill: '#10b981' },
      { name: 'DARPA', value: 1200000, fill: '#ef4444' },
    ],
    categories: [
      { name: 'Artificial Intelligence', value: 32, fill: '#3b82f6' },
      { name: 'Medical Imaging', value: 24, fill: '#8b5cf6' },
      { name: 'NLP', value: 18, fill: '#06b6d4' },
      { name: 'Healthcare', value: 14, fill: '#10b981' },
      { name: 'Robotics', value: 7, fill: '#f59e0b' },
      { name: 'Other', value: 5, fill: '#71717a' },
    ],
    matchDistribution: [
      { range: '90–100%', count: 7, fill: '#10b981' },
      { range: '80–89%', count: 6, fill: '#3b82f6' },
      { range: '70–79%', count: 5, fill: '#f59e0b' },
    ],
    deadlineTimeline: [
      { month: 'Aug 2026', grants: 4, label: 'Aug' },
      { month: 'Sep 2026', grants: 6, label: 'Sep' },
      { month: 'Oct 2026', grants: 3, label: 'Oct' },
      { month: 'Nov 2026', grants: 3, label: 'Nov' },
      { month: 'Dec 2026', grants: 2, label: 'Dec' },
    ],
  },

  deadlines: [
    {
      id: 'dl_01',
      grantTitle: 'AI-Driven Healthcare Diagnostics',
      agency: 'NIH',
      deadline: '2026-08-25',
      priority: 'high',
      funding: 500000,
      matchScore: 96,
    },
    {
      id: 'dl_02',
      grantTitle: 'Federated Learning for Privacy-Preserving AI',
      agency: 'NSF',
      deadline: '2026-09-20',
      priority: 'high',
      funding: 320000,
      matchScore: 94,
    },
    {
      id: 'dl_03',
      grantTitle: 'NLP for Accessibility Tools',
      agency: 'NSF',
      deadline: '2026-09-01',
      priority: 'medium',
      funding: 275000,
      matchScore: 91,
    },
    {
      id: 'dl_04',
      grantTitle: 'Ethical AI Frameworks for Defense',
      agency: 'DARPA',
      deadline: '2026-10-15',
      priority: 'medium',
      funding: 1200000,
      matchScore: 85,
    },
    {
      id: 'dl_05',
      grantTitle: 'Explainable AI for Clinical Decision Support',
      agency: 'ANRF',
      deadline: '2026-10-30',
      priority: 'low',
      funding: 420000,
      matchScore: 82,
    },
  ],
};

// ---------- Discover Grants (with match reasons) ----------
export const discoverGrants = [
  {
    id: 'grant_01',
    title: 'AI-Driven Healthcare Diagnostics',
    agency: 'NIH',
    funding: 500000,
    deadline: '2026-08-25',
    country: 'USA',
    tags: ['AI', 'Healthcare', 'Medical Imaging', 'Diagnostics'],
    description: 'Develop novel AI-based diagnostic tools for early disease detection using multi-modal patient data and medical imaging.',
    eligibility: 'US-based research institutions',
    matchScore: 96,
    priority: 'high',
    status: 'open',
    postedDate: '2026-06-15',
    isBookmarked: true,
    matchReasons: ['Artificial Intelligence', 'Medical Imaging', 'Healthcare'],
    whyMatch: 'Directly aligns with your AI healthcare diagnostics and medical imaging research.',
  },
  {
    id: 'grant_02',
    title: 'Deep Learning for Genomic Analysis',
    agency: 'NSF',
    funding: 350000,
    deadline: '2026-09-10',
    country: 'USA',
    tags: ['Deep Learning', 'Genomics', 'Bioinformatics'],
    description: 'Apply deep learning architectures to analyze large-scale genomic datasets for precision medicine.',
    eligibility: 'Accredited universities and research labs',
    matchScore: 92,
    priority: 'high',
    status: 'open',
    postedDate: '2026-07-01',
    isBookmarked: false,
    matchReasons: ['Deep Learning', 'Healthcare', 'AI'],
    whyMatch: 'Your deep learning expertise and healthcare informatics background are a strong fit.',
  },
  {
    id: 'grant_03',
    title: 'Climate Prediction with Machine Learning',
    agency: 'DOE',
    funding: 750000,
    deadline: '2026-08-30',
    country: 'USA',
    tags: ['Machine Learning', 'Climate', 'Earth Science'],
    description: 'Leverage ML models to improve climate prediction accuracy and extreme weather forecasting.',
    eligibility: 'National laboratories and universities',
    matchScore: 74,
    priority: 'low',
    status: 'open',
    postedDate: '2026-06-20',
    isBookmarked: false,
    matchReasons: ['Machine Learning'],
    whyMatch: 'Partial overlap with your ML expertise; cross-disciplinary opportunity.',
  },
  {
    id: 'grant_04',
    title: 'Ethical AI Frameworks for Defense',
    agency: 'DARPA',
    funding: 1200000,
    deadline: '2026-10-15',
    country: 'USA',
    tags: ['AI Ethics', 'Defense', 'Responsible AI', 'Policy'],
    description: 'Research and develop ethical frameworks for responsible AI deployment in defense systems.',
    eligibility: 'US institutions with security clearance',
    matchScore: 85,
    priority: 'medium',
    status: 'open',
    postedDate: '2026-07-10',
    isBookmarked: false,
    matchReasons: ['Artificial Intelligence', 'Responsible AI'],
    whyMatch: 'Your AI research aligns with the responsible deployment focus of this grant.',
  },
  {
    id: 'grant_05',
    title: 'Natural Language Processing for Accessibility',
    agency: 'NSF',
    funding: 275000,
    deadline: '2026-09-01',
    country: 'USA',
    tags: ['NLP', 'Accessibility', 'HCI', 'Clinical NLP'],
    description: 'Develop NLP-powered tools to enhance digital accessibility for users with disabilities.',
    eligibility: 'US academic institutions',
    matchScore: 91,
    priority: 'high',
    status: 'open',
    postedDate: '2026-06-25',
    isBookmarked: false,
    matchReasons: ['NLP', 'Clinical NLP', 'AI'],
    whyMatch: 'Strong alignment with your NLP and clinical text processing expertise.',
  },
  {
    id: 'grant_06',
    title: 'Federated Learning for Privacy-Preserving AI',
    agency: 'NSF',
    funding: 320000,
    deadline: '2026-09-20',
    country: 'USA',
    tags: ['Federated Learning', 'Privacy', 'AI', 'Distributed ML'],
    description: 'Research federated learning approaches that enable collaborative ML while preserving data privacy.',
    eligibility: 'US universities and research institutes',
    matchScore: 94,
    priority: 'high',
    status: 'open',
    postedDate: '2026-06-30',
    isBookmarked: true,
    matchReasons: ['Federated Learning', 'AI', 'Deep Learning'],
    whyMatch: 'Your federated learning keyword and privacy-preserving ML work match precisely.',
  },
  {
    id: 'grant_07',
    title: 'Explainable AI for Clinical Decision Support',
    agency: 'ANRF',
    funding: 420000,
    deadline: '2026-10-30',
    country: 'India',
    tags: ['Explainable AI', 'Clinical AI', 'Healthcare', 'Medical Imaging'],
    description: 'Develop interpretable AI models for clinical decision support systems in radiology and pathology.',
    eligibility: 'Research institutions with clinical partnerships',
    matchScore: 93,
    priority: 'high',
    status: 'open',
    postedDate: '2026-07-12',
    isBookmarked: false,
    matchReasons: ['Medical Imaging', 'Radiology AI', 'Healthcare', 'AI'],
    whyMatch: 'Highly relevant to your Radiology AI keyword and medical imaging research focus.',
  },
  {
    id: 'grant_08',
    title: 'Multi-Modal AI for Drug Repurposing',
    agency: 'NIH',
    funding: 900000,
    deadline: '2026-11-01',
    country: 'USA',
    tags: ['Multi-modal Learning', 'Drug Discovery', 'AI', 'Pharma'],
    description: 'Apply multi-modal AI combining imaging, text, and molecular data to discover drug repurposing candidates.',
    eligibility: 'Research institutions with clinical data access',
    matchScore: 88,
    priority: 'medium',
    status: 'open',
    postedDate: '2026-07-15',
    isBookmarked: false,
    matchReasons: ['Multi-modal Learning', 'AI', 'Healthcare'],
    whyMatch: 'Connects your multi-modal learning keyword with healthcare informatics expertise.',
  },
  {
    id: 'grant_09',
    title: 'AI and Robotics for Surgical Assistance',
    agency: 'UKRI',
    funding: 540000,
    deadline: '2026-09-28',
    country: 'UK',
    tags: ['AI', 'Robotics', 'Surgery', 'Medical Imaging'],
    description: 'Develop AI-assisted robotic systems for minimally invasive surgical procedures using real-time imaging.',
    eligibility: 'UK and international research collaborations',
    matchScore: 82,
    priority: 'medium',
    status: 'open',
    postedDate: '2026-07-08',
    isBookmarked: false,
    matchReasons: ['AI', 'Medical Imaging'],
    whyMatch: 'Your medical imaging expertise is relevant to real-time surgical imaging AI.',
  },
  {
    id: 'grant_10',
    title: 'Transformer Models for Biomedical Text Mining',
    agency: 'Horizon EU',
    funding: 950000,
    deadline: '2026-11-15',
    country: 'EU',
    tags: ['Transformer Models', 'NLP', 'Biomedical', 'Text Mining'],
    description: 'Advance transformer-based NLP for biomedical literature mining, entity recognition, and knowledge graph construction.',
    eligibility: 'European and associated country institutions',
    matchScore: 90,
    priority: 'high',
    status: 'open',
    postedDate: '2026-07-20',
    isBookmarked: false,
    matchReasons: ['Transformer Models', 'NLP', 'Clinical NLP'],
    whyMatch: 'Directly targets your transformer models and clinical NLP keyword profile.',
  },
];

export const grantCategories = [
  { id: 'cat_01', name: 'All Grants', count: 18 },
  { id: 'cat_02', name: 'Artificial Intelligence', count: 10 },
  { id: 'cat_03', name: 'Medical Imaging', count: 5 },
  { id: 'cat_04', name: 'NLP', count: 4 },
  { id: 'cat_05', name: 'Healthcare', count: 6 },
  { id: 'cat_06', name: 'Federated Learning', count: 2 },
  { id: 'cat_07', name: 'Robotics', count: 2 },
  { id: 'cat_08', name: 'Explainable AI', count: 2 },
];

// ---------- Planner (AI-generated, grant-referenced) ----------
export const plannerTasks = [
  {
    id: 'task_01',
    title: 'Read Eligibility Guidelines',
    grantRef: 'AI-Driven Healthcare Diagnostics (NIH)',
    status: 'done',
    priority: 'high',
    category: 'Week 1 — Research',
    dueDate: '2026-08-04',
    description: 'Review NIH R01 eligibility requirements, special emphasis panels, and submission portal instructions.',
    subtasks: [
      { id: 'sub_01', title: 'Review NIH R01 eligibility criteria', completed: true },
      { id: 'sub_02', title: 'Identify required certifications', completed: true },
      { id: 'sub_03', title: 'Confirm institutional approval status', completed: true },
    ],
  },
  {
    id: 'task_02',
    title: 'Collect Recommendation Letters',
    grantRef: 'AI-Driven Healthcare Diagnostics (NIH)',
    status: 'in_progress',
    priority: 'high',
    category: 'Week 2 — Documentation',
    dueDate: '2026-08-11',
    description: 'Request and collect letters of support from collaborating institutions and clinical partners.',
    subtasks: [
      { id: 'sub_04', title: 'Stanford Medical Center letter', completed: true },
      { id: 'sub_05', title: 'MIT CSAIL collaboration letter', completed: false },
      { id: 'sub_06', title: 'Industry partner endorsement', completed: false },
    ],
  },
  {
    id: 'task_03',
    title: 'Prepare Research Proposal Draft',
    grantRef: 'AI-Driven Healthcare Diagnostics (NIH)',
    status: 'in_progress',
    priority: 'high',
    category: 'Week 3 — Proposal',
    dueDate: '2026-08-18',
    description: 'Draft the specific aims, research strategy, and innovation sections using your AI & Medical Imaging expertise.',
    subtasks: [
      { id: 'sub_07', title: 'Write Specific Aims page', completed: true },
      { id: 'sub_08', title: 'Draft Research Strategy section', completed: false },
      { id: 'sub_09', title: 'Prepare Innovation statement', completed: false },
      { id: 'sub_10', title: 'Include preliminary data from publications', completed: false },
    ],
  },
  {
    id: 'task_04',
    title: 'Budget Justification & Facilities',
    grantRef: 'AI-Driven Healthcare Diagnostics (NIH)',
    status: 'todo',
    priority: 'high',
    category: 'Week 3 — Budget',
    dueDate: '2026-08-18',
    description: 'Prepare detailed budget justification including personnel costs, GPU compute, and clinical data access fees.',
    subtasks: [
      { id: 'sub_11', title: 'Personnel costs breakdown', completed: false },
      { id: 'sub_12', title: 'GPU compute & cloud costs', completed: false },
      { id: 'sub_13', title: 'Clinical data licensing fees', completed: false },
      { id: 'sub_14', title: 'Facilities & equipment description', completed: false },
    ],
  },
  {
    id: 'task_05',
    title: 'Submit Final Application',
    grantRef: 'AI-Driven Healthcare Diagnostics (NIH)',
    status: 'todo',
    priority: 'high',
    category: 'Week 4 — Submission',
    dueDate: '2026-08-25',
    description: 'Compile all sections, get internal PI review, and submit via eRA Commons before the NIH deadline.',
    subtasks: [
      { id: 'sub_15', title: 'Compile all proposal sections', completed: false },
      { id: 'sub_16', title: 'Internal department review', completed: false },
      { id: 'sub_17', title: 'Submit via eRA Commons / Grants.gov', completed: false },
    ],
  },
  {
    id: 'task_06',
    title: 'IRB Protocol Submission',
    grantRef: 'AI-Driven Healthcare Diagnostics (NIH)',
    status: 'review',
    priority: 'medium',
    category: 'Week 2 — Compliance',
    dueDate: '2026-08-10',
    description: 'Submit IRB protocol for human subjects research involving patient imaging data.',
    subtasks: [
      { id: 'sub_18', title: 'Draft IRB protocol', completed: true },
      { id: 'sub_19', title: 'Prepare consent forms', completed: true },
      { id: 'sub_20', title: 'Risk assessment document', completed: true },
      { id: 'sub_21', title: 'Submit to IRB office', completed: false },
    ],
  },
];

export const plannerColumns = [
  { id: 'col_todo', title: 'To Do', status: 'todo' },
  { id: 'col_in_progress', title: 'In Progress', status: 'in_progress' },
  { id: 'col_review', title: 'Review', status: 'review' },
  { id: 'col_done', title: 'Done', status: 'done' },
];

// ---------- Notifications (grant-specific) ----------
export const notifications = [
  {
    id: 'notif_01',
    type: 'new_grant',
    title: 'New Grant Matched Your Profile',
    message: '"Explainable AI for Clinical Decision Support" (ANRF) matches your Medical Imaging & Radiology AI expertise — 93% match.',
    timestamp: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
    read: false,
    group: 'Today',
  },
  {
    id: 'notif_02',
    type: 'deadline',
    title: 'Deadline Approaching in 25 Days',
    message: 'NIH "AI-Driven Healthcare Diagnostics" deadline is August 25. Your application planner is 33% complete.',
    timestamp: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    read: false,
    group: 'Today',
  },
  {
    id: 'notif_03',
    type: 'planner',
    title: 'Proposal Checklist Updated',
    message: 'AI auto-generated a 4-week submission plan for your NIH AI Healthcare grant application.',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    read: false,
    group: 'Today',
  },
  {
    id: 'notif_04',
    type: 'planner',
    title: 'Planner Task Due Tomorrow',
    message: 'Collect Recommendation Letters — Stanford Medical Center letter still pending.',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    read: false,
    group: 'Today',
  },
  {
    id: 'notif_05',
    type: 'status',
    title: 'Grant Status Changed',
    message: 'NSF "Federated Learning for Privacy-Preserving AI" status changed from Draft to Open. 94% match with your profile.',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 25).toISOString(),
    read: true,
    group: 'Yesterday',
  },
  {
    id: 'notif_06',
    type: 'new_grant',
    title: 'High-Priority Match Found',
    message: '"Transformer Models for Biomedical Text Mining" (Horizon EU, €950K) matches your NLP & Transformer Models keywords — 90% match.',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 28).toISOString(),
    read: true,
    group: 'Yesterday',
  },
  {
    id: 'notif_07',
    type: 'deadline',
    title: 'Deadline Reminder',
    message: 'DOE Climate Prediction ML grant closes Aug 30. Match score: 74% — partial overlap with your ML expertise.',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
    read: true,
    group: 'Earlier',
  },
  {
    id: 'notif_08',
    type: 'status',
    title: 'Application Status Update',
    message: 'Your DARPA Ethical AI Frameworks proposal has been received and is under administrative review.',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 96).toISOString(),
    read: true,
    group: 'Earlier',
  },
];

// ---------- Settings ----------
export const settingsData = {
  profile: {
    name: 'Dr. Sarah Chen',
    email: 'sarah.chen@stanford.edu',
    institution: 'Stanford University',
    department: 'Computer Science',
    country: 'USA',
    position: 'Associate Professor',
    bio: 'Principal Investigator specializing in AI-driven healthcare solutions, with a focus on clinical NLP and diagnostic imaging. 12 years of experience, 47 publications, h-index 22.',
    website: 'https://cs.stanford.edu/~schen',
    orcid: '0000-0002-1234-5678',
  },
  researchPrefs: {
    interests: ['Artificial Intelligence', 'Medical Imaging', 'Natural Language Processing', 'Healthcare Informatics'],
    keywords: ['Deep Learning', 'CNN', 'Transformer Models', 'Clinical NLP', 'Radiology AI', 'Multi-modal Learning', 'Federated Learning'],
    preferredAgencies: ['NSF', 'NIH', 'ANRF', 'DARPA', 'UKRI', 'Horizon Europe'],
    preferredCountries: ['USA', 'India', 'UK', 'EU'],
    fundingRange: { min: 100000, max: 1500000 },
    grantTypes: ['Research Grant', 'Fellowship', 'Equipment Grant'],
  },
  appearance: {
    theme: 'dark',
    accentColor: 'blue',
    fontSize: 'medium',
    reducedMotion: false,
    compactMode: false,
  },
  notificationPrefs: {
    emailNotifications: true,
    pushNotifications: true,
    deadlineReminders: true,
    newGrantAlerts: true,
    applicationUpdates: true,
    weeklyDigest: true,
    reminderDaysBefore: 7,
  },
};
